# PyCity Schools Analysis

* As a whole, schools with higher budgets, did not yield better test results. By contrast, schools with higher spending per student actually (\$645-675) underperformed compared to schools with smaller budgets (<\$585 per student).

* As a whole, smaller and medium sized schools dramatically out-performed large sized schools on passing math performances (89-91% passing vs 67%).

* As a whole, charter schools out-performed the public district schools across all metrics. However, more analysis will be required to glean if the effect is due to school practices or the fact that charter schools tend to serve smaller student populations per school. 
---

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

# Read School and Student Data File and store into Pandas Data Frames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])

school_data =  school_data.sort_values('school_name',ascending=True)
school_data_complete =  school_data_complete.sort_values('school_name',ascending=True)


In [2]:
school_data

School ID            school_name      type  size   budget
7           7     Bailey High School  District  4976  3124928
6           6    Cabrera High School   Charter  1858  1081356
1           1   Figueroa High School  District  2949  1884411
13         13       Ford High School  District  2739  1763916
4           4    Griffin High School   Charter  1468   917500
3           3  Hernandez High School  District  4635  3022020
8           8     Holden High School   Charter   427   248087
0           0      Huang High School  District  2917  1910635
12         12    Johnson High School  District  4761  3094650
9           9       Pena High School   Charter   962   585858
11         11  Rodriguez High School  District  3999  2547363
2           2    Shelton High School   Charter  1761  1056600
14         14     Thomas High School   Charter  1635  1043130
5           5     Wilson High School   Charter  2283  1319574
10         10     Wright High School   Charter  1800  1049400

## District Summary

* Calculate the total number of schools

* Calculate the total number of students

* Calculate the total budget

* Calculate the average math score 

* Calculate the average reading score

* Calculate the overall passing rate (overall average score), i.e. (avg. math score + avg. reading score)/2

* Calculate the percentage of students with a passing math score (70 or greater)

* Calculate the percentage of students with a passing reading score (70 or greater)

* Create a dataframe to hold the above results

* Optional: give the displayed data cleaner formatting

In [3]:
school_data_complete.head()

Student ID      student_name gender grade         school_name  \
19584       19584        Tammie Fox      F  11th  Bailey High School   
21193       21193   Jennifer Murray      F   9th  Bailey High School   
21192       21192       Lisa Pineda      F   9th  Bailey High School   
21191       21191    Cameron Miller      M  11th  Bailey High School   
21190       21190  Thomas Rasmussen      M  12th  Bailey High School   

       reading_score  math_score  School ID      type  size   budget  
19584             82          92          7  District  4976  3124928  
21193             88          89          7  District  4976  3124928  
21192             86          67          7  District  4976  3124928  
21191             70          75          7  District  4976  3124928  
21190             77          82          7  District  4976  3124928

In [4]:
groupedcomplete = school_data_complete.groupby('school_name')

print(groupedcomplete)

In [5]:
groupedSchool = school_data_complete.groupby('school_name').sum()
groupedSchool

Student ID  reading_score  math_score  School ID  \
school_name                                                               
Bailey High School      101303896         403225      383393      34832   
Cabrera High School      31477307         156027      154329      11148   
Figueroa High School     12949059         239335      226223       2949   
Ford High School         99055935         221164      211184      35607   
Griffin High School      19077394         123043      122360       5872   
Hernandez High School    46090440         375131      358238      13905   
Holden High School        9846620          35789       35784       3416   
Huang High School         4252986         236810      223528          0   
Johnson High School     154327815         385481      366942      57132   
Pena High School         22851829          80851       80654       8658   
Rodriguez High School   112111965         322898      307294      43989   
Shelton High School      11879706         147441      146796       3522   
Thomas High School       62705520         137093      136389      22890   
Wilson High School       33950493         191748      190115      11415   
Wright High School       45243900         151119      150628      18000   

                           size       budget  
school_name                                   
Bailey High School     24760576  15549641728  
Cabrera High School     3452164   2009159448  
Figueroa High School    8696601   5557128039  
Ford High School        7502121   4831365924  
Griffin High School     2155024   1346890000  
Hernandez High School  21483225  14007062700  
Holden High School       182329    105933149  
Huang High School       8508889   5573322295  
Johnson High School    22667121  14733628650  
Pena High School         925444    563595396  
Rodriguez High School  15992001  10186904637  
Shelton High School     3101121   1860672600  
Thomas High School      2673225   1705517550  
Wilson High School      5212089   3012587442  
Wright High School      3240000   1888920000

In [6]:
school_data_complete.groupby('school_name').groups.keys()

dict_keys(['Bailey High School', 'Cabrera High School', 'Figueroa High School', 'Ford High School', 'Griffin High School', 'Hernandez High School', 'Holden High School', 'Huang High School', 'Johnson High School', 'Pena High School', 'Rodriguez High School', 'Shelton High School', 'Thomas High School', 'Wilson High School', 'Wright High School'])

In [7]:
schoolCount = school_data_complete['school_name'].nunique()

schoolCount

15

In [8]:
schoolName = pd.Series(school_data_complete['school_name'].unique())
schoolName

0        Bailey High School
1       Cabrera High School
2      Figueroa High School
3          Ford High School
4       Griffin High School
5     Hernandez High School
6        Holden High School
7         Huang High School
8       Johnson High School
9          Pena High School
10    Rodriguez High School
11      Shelton High School
12       Thomas High School
13       Wilson High School
14       Wright High School
dtype: object

In [9]:
students = school_data_complete['student_name'].count()
    
students

39170

In [10]:
totalBudget = school_data['budget'].sum()
totalBudget

24649428

In [11]:
bdgtPerStd = (school_data['budget'].sum())/(school_data_complete['student_name'].count())

bdgtPerStd

629.2935409752362

In [12]:
mathMean = school_data_complete["math_score"].mean()
mathMean

78.98537145774827

In [13]:
readingMean = school_data_complete["reading_score"].mean()

readingMean

81.87784018381414

In [14]:
overallMean = (school_data_complete["reading_score"].mean()+school_data_complete["math_score"].mean())/2
overallMean

80.43160582078121

### to calculate percentages


In [15]:
passingMath=school_data_complete.loc[school_data_complete['math_score'] >= 70, :]

mathPath = passingMath['Student ID'].count()
percentageMath = mathPath / students * 100
percentageMath

74.9808526933878

In [16]:
type(passingMath)

pandas.core.frame.DataFrame

In [17]:
# passMathPct = passingMath.count()/school_data_complete.student_name.count()*100
# passMathPct

In [18]:
passingReading=school_data_complete.loc[school_data_complete['reading_score'] >= 70, ['reading_score']]

passingReading.count()

reading_score    33610
dtype: int64

In [19]:
passReadingPct = passingReading.count()/students*100
percentageReading = passReadingPct[0]
percentageReading

85.80546336482001

In [20]:
distSummary = pd.DataFrame(columns=["Number of Schools","Number of Students","Total Budget",
"Math Average","Reading Average","Overall Average","Passing % Math","Passing % Reading"])

distSummary.loc[0,:]= [
    school_data_complete['school_name'].nunique(),
    school_data_complete['student_name'].count(),
    school_data['budget'].sum(),
    school_data_complete["math_score"].mean(),
    school_data_complete["reading_score"].mean(),
    (school_data_complete["reading_score"].mean()+school_data_complete["math_score"].mean())/2,
    (passingMath.count()/school_data_complete.student_name.count()*100).values[0],
    (passingReading.count()/school_data_complete.student_name.count()*100).values[0]
]
        
distSummary  

Number of Schools Number of Students Total Budget Math Average  \
0                15              39170     24649428      78.9854   

  Reading Average Overall Average Passing % Math Passing % Reading  
0         81.8778         80.4316        74.9809           85.8055

In [21]:
oPassing = (percentageMath + percentageReading) / 2
oPassing

80.39315802910392

In [22]:
schoolStudents = school_data_complete.groupby('school_name').count()['Student ID'].values

schoolStudents





array([4976, 1858, 2949, 2739, 1468, 4635,  427, 2917, 4761,  962, 3999,
       1761, 1635, 2283, 1800], dtype=int64)

In [23]:
school_type= school_data['type']
school_type=school_type.reset_index(drop=True)
school_type

0     District
1      Charter
2     District
3     District
4      Charter
5     District
6      Charter
7     District
8     District
9      Charter
10    District
11     Charter
12     Charter
13     Charter
14     Charter
Name: type, dtype: object

In [24]:
bySchoolBudget = school_data.budget.values
bySchoolBudget

array([3124928, 1081356, 1884411, 1763916,  917500, 3022020,  248087,
       1910635, 3094650,  585858, 2547363, 1056600, 1043130, 1319574,
       1049400], dtype=int64)

In [25]:
perStudentBudget=bySchoolBudget/schoolStudents
perStudentBudget

array([628., 582., 639., 644., 625., 652., 581., 655., 650., 609., 637.,
       600., 638., 578., 583.])

In [26]:
Average_Math_Score = (school_data_complete.groupby('school_name').mean()['math_score']).round(2).values 
Average_Math_Score

array([77.05, 83.06, 76.71, 77.1 , 83.35, 77.29, 83.8 , 76.63, 77.07,
       83.84, 76.84, 83.36, 83.42, 83.27, 83.68])

In [27]:
Average_Read_Score = (school_data_complete.groupby('school_name').mean()['reading_score']).round(2).values

Average_Read_Score

array([81.03, 83.98, 81.16, 80.75, 83.82, 80.93, 83.81, 81.18, 80.97,
       84.04, 80.74, 83.73, 83.85, 83.99, 83.96])

In [28]:
len(school_data_complete)

39170

In [29]:
school_data_complete.loc[school_data_complete['reading_score'] >= 70, ['reading_score']].count() / len(school_data_complete)

reading_score    0.858055
dtype: float64

In [30]:
school_data_complete["passedReading"] = school_data_complete['reading_score'] >= 70



In [31]:
pRdCt = school_data_complete.groupby("school_name")["passedReading"].sum()

In [32]:
fRdCt = school_data_complete.groupby("school_name")["passedReading"].count()

In [33]:
pRdPct = (pRdCt/fRdCt * 100).round(2).values

pRdPct

array([81.93, 97.04, 80.74, 79.3 , 97.14, 80.86, 96.25, 81.32, 81.22,
       95.95, 80.22, 95.85, 97.31, 96.54, 96.61])

In [34]:
school_data_complete['passedMath'] = school_data_complete['math_score'] >= 70
school_data_complete.head()

Student ID      student_name gender grade         school_name  \
19584       19584        Tammie Fox      F  11th  Bailey High School   
21193       21193   Jennifer Murray      F   9th  Bailey High School   
21192       21192       Lisa Pineda      F   9th  Bailey High School   
21191       21191    Cameron Miller      M  11th  Bailey High School   
21190       21190  Thomas Rasmussen      M  12th  Bailey High School   

       reading_score  math_score  School ID      type  size   budget  \
19584             82          92          7  District  4976  3124928   
21193             88          89          7  District  4976  3124928   
21192             86          67          7  District  4976  3124928   
21191             70          75          7  District  4976  3124928   
21190             77          82          7  District  4976  3124928   

       passedReading  passedMath  
19584           True        True  
21193           True        True  
21192           True       False  
21191           True        True  
21190           True        True

In [35]:
pMthCt = school_data_complete.groupby("school_name")["passedMath"].sum()
pMthCt

school_name
Bailey High School       3318.0
Cabrera High School      1749.0
Figueroa High School     1946.0
Ford High School         1871.0
Griffin High School      1371.0
Hernandez High School    3094.0
Holden High School        395.0
Huang High School        1916.0
Johnson High School      3145.0
Pena High School          910.0
Rodriguez High School    2654.0
Shelton High School      1653.0
Thomas High School       1525.0
Wilson High School       2143.0
Wright High School       1680.0
Name: passedMath, dtype: float64

In [36]:
fMthCt = school_data_complete.groupby("school_name")["passedMath"].count()
fMthCt.values

array([4976, 1858, 2949, 2739, 1468, 4635,  427, 2917, 4761,  962, 3999,
       1761, 1635, 2283, 1800], dtype=int64)

In [37]:
pMthPct = (pMthCt/fMthCt * 100).round(2).values

pMthPct

array([66.68, 94.13, 65.99, 68.31, 93.39, 66.75, 92.51, 65.68, 66.06,
       94.59, 66.37, 93.87, 93.27, 93.87, 93.33])

In [38]:
overallPct=((pMthPct+pRdPct)/2).round(2)
overallPct

array([74.31, 95.58, 73.36, 73.81, 95.26, 73.81, 94.38, 73.5 , 73.64,
       95.27, 73.3 , 94.86, 95.29, 95.21, 94.97])

## School Summary

* Create an overview table that summarizes key metrics about each school, including:
  * School Name
  * School Type
  * Total Students
  * Total School Budget
  * Per Student Budget
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)
  
* Create a dataframe to hold the above results

In [39]:
#convert if necessary

overallPctSer = pd.Series(overallPct)
overallPctSer

schoolStudentsSer=pd.Series(schoolStudents)

schoolStudentsSer

bySchoolBudgetSer=pd.Series(bySchoolBudget)

perStudentBudgetSer=pd.Series(perStudentBudget)
Average_Read_ScoreSer=pd.Series(Average_Read_Score)
Average_Math_ScoreSer=pd.Series(Average_Math_Score)
pMthPctSer=pd.Series(pMthPct)
pRdPctSer=pd.Series(pRdPct)


In [40]:
pMthPctSer

0     66.68
1     94.13
2     65.99
3     68.31
4     93.39
5     66.75
6     92.51
7     65.68
8     66.06
9     94.59
10    66.37
11    93.87
12    93.27
13    93.87
14    93.33
dtype: float64

In [41]:
#type(schoolStudents)


In [42]:
#concatenation of each series; need to chk


mstrSrs=(pd.concat([schoolName, school_type, schoolStudentsSer, bySchoolBudgetSer, perStudentBudgetSer,Average_Read_ScoreSer,\
                    Average_Math_ScoreSer,pMthPctSer,pRdPctSer, overallPctSer], axis=1))

mstrSrs.columns=['schoolName','schoolType', 'schoolStudents','bySchoolBudget','perStudentBudget','Average_Read_Score',\
                 'avgMathScore','passMthPct','passRdPct','overallPct']

mstrSrs

schoolName schoolType  schoolStudents  bySchoolBudget  \
0      Bailey High School   District            4976         3124928   
1     Cabrera High School    Charter            1858         1081356   
2    Figueroa High School   District            2949         1884411   
3        Ford High School   District            2739         1763916   
4     Griffin High School    Charter            1468          917500   
5   Hernandez High School   District            4635         3022020   
6      Holden High School    Charter             427          248087   
7       Huang High School   District            2917         1910635   
8     Johnson High School   District            4761         3094650   
9        Pena High School    Charter             962          585858   
10  Rodriguez High School   District            3999         2547363   
11    Shelton High School    Charter            1761         1056600   
12     Thomas High School    Charter            1635         1043130   
13     Wilson High School    Charter            2283         1319574   
14     Wright High School    Charter            1800         1049400   

    perStudentBudget  Average_Read_Score  avgMathScore  passMthPct  passRdPct  \
0              628.0               81.03         77.05       66.68      81.93   
1              582.0               83.98         83.06       94.13      97.04   
2              639.0               81.16         76.71       65.99      80.74   
3              644.0               80.75         77.10       68.31      79.30   
4              625.0               83.82         83.35       93.39      97.14   
5              652.0               80.93         77.29       66.75      80.86   
6              581.0               83.81         83.80       92.51      96.25   
7              655.0               81.18         76.63       65.68      81.32   
8              650.0               80.97         77.07       66.06      81.22   
9              609.0               84.04         83.84       94.59      95.95   
10             637.0               80.74         76.84       66.37      80.22   
11             600.0               83.73         83.36       93.87      95.85   
12             638.0               83.85         83.42       93.27      97.31   
13             578.0               83.99         83.27       93.87      96.54   
14             583.0               83.96         83.68       93.33      96.61   

    overallPct  
0        74.31  
1        95.58  
2        73.36  
3        73.81  
4        95.26  
5        73.81  
6        94.38  
7        73.50  
8        73.64  
9        95.27  
10       73.30  
11       94.86  
12       95.29  
13       95.21  
14       94.97

In [44]:
mstrSrs.transpose()

0                    1   \
schoolName          Bailey High School  Cabrera High School   
schoolType                    District              Charter   
schoolStudents                    4976                 1858   
bySchoolBudget                 3124928              1081356   
perStudentBudget                   628                  582   
Average_Read_Score               81.03                83.98   
avgMathScore                     77.05                83.06   
passMthPct                       66.68                94.13   
passRdPct                        81.93                97.04   
overallPct                       74.31                95.58   

                                      2                 3   \
schoolName          Figueroa High School  Ford High School   
schoolType                      District          District   
schoolStudents                      2949              2739   
bySchoolBudget                   1884411           1763916   
perStudentBudget                     639               644   
Average_Read_Score                 81.16             80.75   
avgMathScore                       76.71              77.1   
passMthPct                         65.99             68.31   
passRdPct                          80.74              79.3   
overallPct                         73.36             73.81   

                                     4                      5   \
schoolName          Griffin High School  Hernandez High School   
schoolType                      Charter               District   
schoolStudents                     1468                   4635   
bySchoolBudget                   917500                3022020   
perStudentBudget                    625                    652   
Average_Read_Score                83.82                  80.93   
avgMathScore                      83.35                  77.29   
passMthPct                        93.39                  66.75   
passRdPct                         97.14                  80.86   
overallPct                        95.26                  73.81   

                                    6                  7   \
schoolName          Holden High School  Huang High School   
schoolType                     Charter           District   
schoolStudents                     427               2917   
bySchoolBudget                  248087            1910635   
perStudentBudget                   581                655   
Average_Read_Score               83.81              81.18   
avgMathScore                      83.8              76.63   
passMthPct                       92.51              65.68   
passRdPct                        96.25              81.32   
overallPct                       94.38               73.5   

                                     8                 9   \
schoolName          Johnson High School  Pena High School   
schoolType                     District           Charter   
schoolStudents                     4761               962   
bySchoolBudget                  3094650            585858   
perStudentBudget                    650               609   
Average_Read_Score                80.97             84.04   
avgMathScore                      77.07             83.84   
passMthPct                        66.06             94.59   
passRdPct                         81.22             95.95   
overallPct                        73.64             95.27   

                                       10                   11  \
schoolName          Rodriguez High School  Shelton High School   
schoolType                       District              Charter   
schoolStudents                       3999                 1761   
bySchoolBudget                    2547363              1056600   
perStudentBudget                      637                  600   
Average_Read_Score                  80.74                83.73   
avgMathScore                        76.84                83.36   
passMthPct                          66.37                93.

## Top Performing Schools (By Passing Rate)

* Sort and display the top five schools in overall passing rate

In [45]:
topPassingRate = mstrSrs.sort_values('overallPct',ascending=False)
topPassingRate.head()

schoolName schoolType  schoolStudents  bySchoolBudget  \
1   Cabrera High School    Charter            1858         1081356   
12   Thomas High School    Charter            1635         1043130   
9      Pena High School    Charter             962          585858   
4   Griffin High School    Charter            1468          917500   
13   Wilson High School    Charter            2283         1319574   

    perStudentBudget  Average_Read_Score  avgMathScore  passMthPct  passRdPct  \
1              582.0               83.98         83.06       94.13      97.04   
12             638.0               83.85         83.42       93.27      97.31   
9              609.0               84.04         83.84       94.59      95.95   
4              625.0               83.82         83.35       93.39      97.14   
13             578.0               83.99         83.27       93.87      96.54   

    overallPct  
1        95.58  
12       95.29  
9        95.27  
4        95.26  
13       95.21

## Bottom Performing Schools (By Passing Rate)

* Sort and display the five worst-performing schools

In [46]:
bottomPassingRate = mstrSrs.sort_values('overallPct',ascending=True)
bottomPassingRate.head()

schoolName schoolType  schoolStudents  bySchoolBudget  \
10  Rodriguez High School   District            3999         2547363   
2    Figueroa High School   District            2949         1884411   
7       Huang High School   District            2917         1910635   
8     Johnson High School   District            4761         3094650   
3        Ford High School   District            2739         1763916   

    perStudentBudget  Average_Read_Score  avgMathScore  passMthPct  passRdPct  \
10             637.0               80.74         76.84       66.37      80.22   
2              639.0               81.16         76.71       65.99      80.74   
7              655.0               81.18         76.63       65.68      81.32   
8              650.0               80.97         77.07       66.06      81.22   
3              644.0               80.75         77.10       68.31      79.30   

    overallPct  
10       73.30  
2        73.36  
7        73.50  
8        73.64  
3        73.81

## Math Scores by Grade

* Create a table that lists the average Reading Score for students of each grade level (9th, 10th, 11th, 12th) at each school.

  * Create a pandas series for each grade. Hint: use a conditional statement.
  
  * Group each series by school
  
  * Combine the series into a dataframe
  
  * Optional: give the displayed data cleaner formatting

In [47]:
'''rows represent school names, columns represent grades





'''

'rows represent school names, columns represent grades\n\n\n\n\n\n'

## Reading Score by Grade 

* Perform the same operations as above for reading scores

## Scores by School Spending

* Create a table that breaks down school performances based on average Spending Ranges (Per Student). Use 4 reasonable bins to group school spending. Include in the table each of the following:
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)

In [63]:
# Sample bins. Feel free to create your own bins.
spending_bins = [0, 585, 615, 645, 675]
group_names = ["<$585", "$585-615", "$615-645", "$645-675"]

In [69]:
mstrSrs['spending_bins']=pd.cut(mstrSrs['perStudentBudget'],spending_bins,labels=group_names)

bBinMstrSrs=mstrSrs.groupby(['spending_bins']).mean()
bBinMstrSrs.drop(['schoolStudents','bySchoolBudget','perStudentBudget'],axis=1, inplace=True)
bBinMstrSrs

Average_Read_Score  avgMathScore  passMthPct  passRdPct  \
spending_bins                                                            
<$585                   83.935000     83.452500   93.460000  96.610000   
$585-615                83.885000     83.600000   94.230000  95.900000   
$615-645                81.891667     79.078333   75.668333  86.106667   
$645-675                81.026667     76.996667   66.163333  81.133333   

               overallPct  
spending_bins              
<$585           95.035000  
$585-615        95.065000  
$615-645        80.888333  
$645-675        73.650000

## Scores by School Size

* Perform the same operations as above, based on school size.

In [55]:
# Sample bins. Feel free to create your own bins.
size_bins = [0, 1000, 2000, 5000]
group_names = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]

In [57]:
mstrSrs['size_bins']=pd.cut(mstrSrs['schoolStudents'],size_bins,labels=group_names)
mstrSrs

schoolName schoolType  schoolStudents  bySchoolBudget  \
0      Bailey High School   District            4976         3124928   
1     Cabrera High School    Charter            1858         1081356   
2    Figueroa High School   District            2949         1884411   
3        Ford High School   District            2739         1763916   
4     Griffin High School    Charter            1468          917500   
5   Hernandez High School   District            4635         3022020   
6      Holden High School    Charter             427          248087   
7       Huang High School   District            2917         1910635   
8     Johnson High School   District            4761         3094650   
9        Pena High School    Charter             962          585858   
10  Rodriguez High School   District            3999         2547363   
11    Shelton High School    Charter            1761         1056600   
12     Thomas High School    Charter            1635         1043130   
13     Wilson High School    Charter            2283         1319574   
14     Wright High School    Charter            1800         1049400   

    perStudentBudget  Average_Read_Score  avgMathScore  passMthPct  passRdPct  \
0              628.0               81.03         77.05       66.68      81.93   
1              582.0               83.98         83.06       94.13      97.04   
2              639.0               81.16         76.71       65.99      80.74   
3              644.0               80.75         77.10       68.31      79.30   
4              625.0               83.82         83.35       93.39      97.14   
5              652.0               80.93         77.29       66.75      80.86   
6              581.0               83.81         83.80       92.51      96.25   
7              655.0               81.18         76.63       65.68      81.32   
8              650.0               80.97         77.07       66.06      81.22   
9              609.0               84.04         83.84       94.59      95.95   
10             637.0               80.74         76.84       66.37      80.22   
11             600.0               83.73         83.36       93.87      95.85   
12             638.0               83.85         83.42       93.27      97.31   
13             578.0               83.99         83.27       93.87      96.54   
14             583.0               83.96         83.68       93.33      96.61   

    overallPct spending_bins           size_bins  
0        74.31      $615-645   Large (2000-5000)  
1        95.58         <$585  Medium (1000-2000)  
2        73.36      $615-645   Large (2000-5000)  
3        73.81      $615-645   Large (2000-5000)  
4        95.26      $615-645  Medium (1000-2000)  
5        73.81      $645-675   Large (2000-5000)  
6        94.38         <$585       Small (<1000)  
7        73.50      $645-675   Large (2000-5000)  
8        73.64      $645-675   Large (2000-5000)  
9        95.27      $585-615       Small (<1000)  
10       73.30      $615-645   Large (2000-5000)  
11       94.86      $585-615  Medium (1000-2000)  
12       95.29      $615-645  Medium (1000-2000)  
13       95.21         <$585   Large (2000-5000)  
14       94.97         <$585  Medium (1000-2000)

## Scores by School Type

* Perform the same operations as above, based on school type.

In [70]:
byDistMstrSrs=mstrSrs.groupby(['schoolType']).mean()
byDistMstrSrs

schoolStudents  bySchoolBudget  perStudentBudget  \
schoolType                                                     
Charter        1524.250000    9.126881e+05        599.500000   
District       3853.714286    2.478275e+06        643.571429   

            Average_Read_Score  avgMathScore  passMthPct  passRdPct  \
schoolType                                                            
Charter              83.897500     83.472500   93.620000  96.586250   
District             80.965714     76.955714   66.548571  80.798571   

            overallPct  
schoolType              
Charter      95.102500  
District     73.675714

In [58]:
group_names = ['Charter','District']

In [60]:
mstrSrs=pd.cut(mstrSrs['schoolType'],type_bins,labels=group_names)

TypeError: '<' not supported between instances of 'int' and 'str'